# -*- coding: utf-8 -*-
"""Copy of Final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oNqZcwqIWxvVYfHUzHnuUt9o1Vxqww-o
"""

import logging, sys
logging.disable(sys.maxsize)

import poe
client = poe.Client("UGvbFTUKodZgxSHi0Rmn4Q%3D%3D")

import logging
import sys
import json

#get the account's bot list

token = sys.argv[1]
poe.logger.setLevel(logging.INFO)

print(json.dumps(client.bot_names, indent=2))

data = input().split(',')

#print(data)

#client.send_message("acouchy", data, with_chat_break=True)#palm called

def split(a, n):
    k, m = divmod(len(a), n)
    return (a[i*k+min(i, m):(i+1)*k+min(i+1, m)] for i in range(n))

txt = list(split(data,5))

prompt1 = 'Find the domain/theme of '+str(txt[0])+' in one word'
prompt2 = 'Find the domain/theme of '+str(txt[1])+' in one word'
prompt3 = 'Find the domain/theme of '+str(txt[2])+' in one word'
prompt4 = 'Find the domain/theme of '+str(txt[3])+' in one word'
prompt5 = 'Find the domain/theme of '+str(txt[4])+' in one word'

list_theme = []

for i in client.send_message("acouchy",prompt1, with_chat_break=True):
  text1 = i["text_new"]
  list_theme.append(text1)

for i in client.send_message("acouchy",prompt2, with_chat_break=True):
  text2 = i["text_new"]
  list_theme.append(text2)

for i in client.send_message("acouchy",prompt3, with_chat_break=True):
  text3 = i["text_new"]
  list_theme.append(text3)

for i in client.send_message("acouchy",prompt4, with_chat_break=True):
  text4 = i["text_new"]
  list_theme.append(text4)

for i in client.send_message("acouchy",prompt5, with_chat_break=True):
  text5 = i["text_new"]
  list_theme.append(text5)
